version: '2'
services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/nginx/conf/conf.d:/etc/nginx/conf.d
      - ~/nginx/conf/vhost.d:/etc/nginx/vhost.d
      - ~/nginx/conf/nginx.conf:/etc/nginx/nginx.conf

  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
